window:
  padding:
    x: 10
    y: 10
font:
  normal:
    family: "Source Code Pro"
    style: Normal
  bold:
    family: "Source Code Pro"
    style: Bold
  italic:
    family: "Source Code Pro"
    style: Italic
  size: 7.5
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0

# Colors (Base16 Default Dark)
colors:
  # Default colors
  primary:
    background: '0x181818'
    foreground: '0xd8d8d8'

  # Colors the cursor will use if `custom_cursor_colors` is true
  cursor:
    text: '0xd8d8d8'
    cursor: '0xd8d8d8'

  # Normal colors
  normal:
    black:   '0x181818'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xd8d8d8'

  # Bright colors
  bright:
    black:   '0x585858'
    red:     '0xab4642'
    green:   '0xa1b56c'
    yellow:  '0xf7ca88'
    blue:    '0x7cafc2'
    magenta: '0xba8baf'
    cyan:    '0x86c1b9'
    white:   '0xf8f8f8'